[package]
name = "tin-lang"
description = "tin: a statically structurally typed embeddable programming language"
license = "MIT"
version = "0.2.2"
authors = ["David Flemström <david.flemstrom@gmail.com>"]
repository = "https://github.com/dflemstr/tin"
edition = "2018"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
cranelift = "0.26.0"
cranelift-module = "0.26.0"
cranelift-simplejit = "0.26.0"
dot = "0.1.4"
env_logger = "0.6.0"
failure = "0.1.5"
lalrpop-util = "0.16.2"
log = "0.4.6"
regex = "1.1.0"
specs = "0.14.2"
specs-derive = "0.4.0"
specs-visitor-derive = { version = "0.2.0", path = "specs-visitor-derive" }
specs-visitor = { version = "0.2.0", path = "specs-visitor" }
pretty_env_logger = "0.3.0"
structopt = "0.2.14"
lazy_static = "1.2.0"
byteorder = "1.2.7"
rayon = "1.0.3"
itertools = "0.8.0"
codespan = "0.2.0"
codespan-reporting = "0.2.0"

[features]
test-render-graphs = []

[profile.release]
debug = true
lto = true
codegen-units = 1

[workspace]
members = ["specs-visitor", "specs-visitor-derive"]

[patch.crates-io]
codemap-diagnostic = { git = "https://github.com/dflemstr/codemap-diagnostic.git", branch = "scoped-emitter" }
