[package]
name = "norm"
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]

[build-dependencies]
lalrpop = "0.16.0"

[dependencies]
lalrpop-util = "0.16.0"
regex = "1.0.5"
failure = "0.1.3"
itertools = "0.7.8"
bimap = "0.1.5"
cranelift = "0.22.0"
cranelift-module = "0.22.0"
cranelift-simplejit = "0.22.0"
