[package]
name = "norm"
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
cranelift = "0.25.0"
cranelift-module = "0.25.0"
cranelift-simplejit = "0.25.0"
dot = "0.1.4"
env_logger = "0.6.0"
failure = "0.1.3"
lalrpop-util = "0.16.2"
log = "0.4.6"
regex = "1.1.0"
specs = "0.14.1"
specs-derive = "0.3.0"
specs-visitor-derive = { path = "specs-visitor-derive" }
specs-visitor = { path = "specs-visitor" }

[profile.release]
debug = true
lto = true
codegen-units = 1

[workspace]
members = ["norm-parser-fuzz-target", "norm-ir-fuzz-target", "specs-visitor", "specs-visitor-derive"]
