version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt-preview
      - run:
          name: Check formatting
          command: cargo fmt --all -- --check
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v3-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - ~/.cargo/registry
            - ./target/debug/.fingerprint
            - ./target/debug/build
            - ./target/debug/deps
          key: v3-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ epoch }}
      - run:
          name: Install coverage prerequisites
          command: .circleci/install-coverage.sh
      - run:
          name: Upload coverage
          command: .circleci/codecov.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: tin
