[package]
name = "specs-visitor"
description = "Utilities for visiting entities in an ECS that is using the specs library."
license = "MIT"
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]

[dependencies]
specs = "0.14.1"
rayon = "1.0.3"
