[package]
name = "norm-parser-fuzz-target"
version = "0.1.0"
authors = ["David Flemström <dflemstr@spotify.com>"]

[dependencies]
afl = "0.4.2"
norm = { path = ".." }

[profile.release]
debug = true
lto = true
codegen-units = 1
